# Generated by Django 5.2.4 on 2025-08-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('date_finished', models.DateField()),
                ('rating', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date_finished'], name='books_book_date_fi_c55fb3_idx'), models.Index(fields=['author'], name='books_book_author_b941fe_idx'), models.Index(fields=['rating'], name='books_book_rating_d06a65_idx')],
            },
        ),
    ]
